export const MEMES = [
  "/memes/foto (1).jpg",
  "/memes/foto (2).jpg",
  "/memes/foto (3).jpg",
  "/memes/foto (4).jpg",
  "/memes/foto (5).jpg",
  "/memes/foto (6).jpg",
  "/memes/foto (7).jpg",
  "/memes/foto (8).jpg",
  "/memes/foto (9).jpg",
  "/memes/foto (10).jpg",
  "/memes/foto (11).jpg",
  "/memes/foto (12).jpg",
  "/memes/foto (13).jpg",
  "/memes/foto (14).jpg",
  "/memes/foto (15).jpg",
  "/memes/foto (16).jpg",
  "/memes/foto (17).jpg",
  "/memes/foto (18).jpg",
  "/memes/foto (19).jpg",
  "/memes/foto (20).jpg",
  "/memes/foto (21).jpg",
  "/memes/foto (22).jpg",
  "/memes/foto (23).jpg",
  "/memes/foto (24).jpg"
];